import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/server/analytics-auth";
import { listManagedProjects, saveManagedProject } from "@/lib/server/portfolio-projects";
import type { Project } from "@/lib/data/projects";
export const dynamic="force-dynamic";
const slugPattern=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const statuses=new Set(["draft","analyzing","needs_info","review","published","archived"]);
function validProject(v:unknown):v is Project {
 if(!v||typeof v!=="object")return false; const p=v as Record<string,unknown>;
 const strings=[p.category,p.type,p.h1,p.shortDescription,p.description,p.problem,p.solution,p.execution,p.objective];
 const list=(value:unknown)=>Array.isArray(value)&&value.length<=40&&value.every(item=>typeof item==="string"&&item.length<=500);
 let safeUrl=false; try{const u=new URL(String(p.url));safeUrl=u.protocol==="https:"&&!u.username&&!u.password&&!u.port&&u.href.length<=2048}catch{safeUrl=p.url===""}
 const cover=p.cover&&typeof p.cover==="object"?p.cover as Record<string,unknown>:{};
 const image=typeof cover.src==="string"&&(cover.src===""||(cover.src.startsWith("/")&&!cover.src.startsWith("//")&&!cover.src.includes("..")));
 const art=cover.art&&typeof cover.art==="object"?cover.art as Record<string,unknown>:{};
 return typeof p.slug==="string"&&slugPattern.test(p.slug)&&typeof p.name==="string"&&p.name.trim().length>=2&&p.name.length<=160&&strings.every(x=>typeof x==="string"&&x.length<=5000)&&list(p.features)&&list(p.decisions)&&list(p.tags)&&list(p.stack)&&safeUrl&&typeof p.updatedAt==="string"&&image&&typeof cover.alt==="string"&&["mimoPet","peredaEngenharia","ortoclinica","draValesca"].includes(String(art.variant))&&typeof art.bg==="string"&&typeof art.fg==="string"&&typeof art.accent==="string";
}
export async function GET(){const denied=await requireAdmin();if(denied)return denied;try{return NextResponse.json({projects:await listManagedProjects()},{headers:{"Cache-Control":"private, no-store"}})}catch{return NextResponse.json({error:"Não foi possível carregar projetos. Verifique Supabase e migration."},{status:503})}}
export async function POST(request:Request){const denied=await requireAdmin();if(denied)return denied;let body:unknown;try{body=await request.json()}catch{return NextResponse.json({error:"Corpo JSON inválido."},{status:400})}if(!body||typeof body!=="object")return NextResponse.json({error:"Dados inválidos."},{status:400});const b=body as Record<string,unknown>;if(!validProject(b.project)||typeof b.status!=="string"||!statuses.has(b.status)||b.status==="published")return NextResponse.json({error:"Projeto inválido. Novos projetos começam como rascunho e não são publicados automaticamente."},{status:400});try{const saved=await saveManagedProject({slug:b.project.slug,project_data:b.project,status:b.status as never,source_url:typeof b.sourceUrl==="string"?b.sourceUrl:null,source_facts:b.sourceFacts&&typeof b.sourceFacts==="object"?b.sourceFacts as Record<string,unknown>:{},pending_confirmations:Array.isArray(b.pendingConfirmations)?b.pendingConfirmations.filter((x):x is string=>typeof x==="string").slice(0,30):[]});return NextResponse.json({project:saved},{status:201})}catch{return NextResponse.json({error:"Não foi possível salvar. Verifique se o slug já existe e se a migration foi aplicada."},{status:503})}}
export async function PATCH(request:Request){const denied=await requireAdmin();if(denied)return denied;let body:unknown;try{body=await request.json()}catch{return NextResponse.json({error:"Corpo JSON inválido."},{status:400})}if(!body||typeof body!=="object")return NextResponse.json({error:"Dados inválidos."},{status:400});const b=body as Record<string,unknown>;if(typeof b.id!=="string"||! /^[0-9a-f-]{36}$/i.test(b.id)||!validProject(b.project)||typeof b.status!=="string"||!statuses.has(b.status))return NextResponse.json({error:"Projeto inválido."},{status:400});if(b.status==="published"&&(!b.project.problem||!b.project.solution||!b.project.execution||!b.project.objective||!b.project.shortDescription))return NextResponse.json({error:"Preencha apresentação, desafio, solução e descrição antes de publicar."},{status:422});if(b.status==="published"&&Array.isArray(b.pendingConfirmations)&&b.pendingConfirmations.length>0)return NextResponse.json({error:"Resolva ou remova as pendências de confirmação antes de publicar."},{status:422});try{const saved=await saveManagedProject({id:b.id,slug:b.project.slug,project_data:b.project,status:b.status as never,source_url:typeof b.sourceUrl==="string"?b.sourceUrl:null,source_facts:b.sourceFacts&&typeof b.sourceFacts==="object"?b.sourceFacts as Record<string,unknown>:{},pending_confirmations:Array.isArray(b.pendingConfirmations)?b.pendingConfirmations.filter((x):x is string=>typeof x==="string").slice(0,30):[]});return NextResponse.json({project:saved},{headers:{"Cache-Control":"no-store"}})}catch{return NextResponse.json({error:"Não foi possível atualizar o projeto."},{status:503})}}
