"use client";
import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import type { Project } from "@/lib/data/projects";
import styles from "./ProjectsAdmin.module.css";
type Status="draft"|"analyzing"|"needs_info"|"review"|"published"|"archived";
type Row={id?:string;slug:string;project_data:Project;status:Status;source_url:string|null;source_facts:Record<string,unknown>;pending_confirmations:string[];updated_at:string};
type Analysis={url:string;title:string|null;description:string|null;imageUrl:string|null;siteName:string|null;fetchedAt:string;notice:string};
const blank=(name=""):Project=>({slug:"",name,category:"A confirmar",type:"Projeto web",h1:name,shortDescription:"",description:"",problem:"Necessidade a confirmar com o responsável pelo projeto.",solution:"",execution:"",objective:"",brandValue:"",businessValue:"",salesValue:"",futureOpportunities:"",features:[],decisions:[],tags:[],stack:[],url:"",updatedAt:new Date().toISOString().slice(0,10),cover:{src:"",alt:"Composição tipográfica ilustrativa, não é captura do site",width:1600,height:1000,art:{variant:"peredaEngenharia",bg:"#110c15",fg:"#f5f2f7",accent:"#b8ff00"}}});
const fieldList=(s:string)=>s.split("\n").map(x=>x.trim()).filter(Boolean);
export function ProjectsAdmin({initialProjects}:{initialProjects:readonly Project[]}){
 const [rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<Row|null>(null),[draft,setDraft]=useState<Project>(blank()),[status,setStatus]=useState<Status>("draft"),[url,setUrl]=useState(""),[analysis,setAnalysis]=useState<Analysis|null>(null),[facts,setFacts]=useState<Record<string,unknown>>({}),[pending,setPending]=useState<string[]>([]),[filter,setFilter]=useState(""),[category,setCategory]=useState("Todos"),[statusFilter,setStatusFilter]=useState("Todos"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[authenticated,setAuthenticated]=useState(false),[password,setPassword]=useState("");
 const headers={"Content-Type":"application/json"};
 async function load(){const r=await fetch("/api/admin/projetos",{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.projects)}
 useEffect(()=>{void (async()=>{try{const r=await fetch("/api/admin/analytics/session",{cache:"no-store"});const d=await r.json();setAuthenticated(Boolean(d.authenticated));if(d.authenticated)await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar o painel")}})()},[]);
 const entries=useMemo(()=>[...initialProjects.map(p=>rows.find(row=>row.slug===p.slug)??({slug:p.slug,project_data:p,status:"published" as const,source_url:p.url,updated_at:p.updatedAt})),...rows.filter(row=>!initialProjects.some(p=>p.slug===row.slug))], [initialProjects,rows]);
 const categories=[...new Set(entries.map(x=>x.project_data.category))];const shown=entries.filter(x=>(!filter||x.project_data.name.toLowerCase().includes(filter.toLowerCase()))&&(category==="Todos"||x.project_data.category===category)&&(statusFilter==="Todos"||x.status===statusFilter));
 function edit(row:Row){setSelected(row);setDraft({...row.project_data});setStatus(row.id?row.status:"review");setUrl(row.source_url??row.project_data.url);setFacts(row.source_facts);setPending(row.pending_confirmations);setAnalysis(null);setError("");setNotice("")}
 function fresh(){setSelected(null);setDraft(blank());setStatus("draft");setUrl("");setFacts({});setPending([]);setAnalysis(null);setError("");setNotice("")}
 async function inspect(){setBusy(true);setError("");setNotice("");setStatus("analyzing");try{const r=await fetch("/api/admin/projetos/analise",{method:"POST",headers,body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw Error(d.error);const a=d.analysis as Analysis;setAnalysis(a);setFacts(a as unknown as Record<string,unknown>);const name=a.siteName??a.title??"Projeto importado";setDraft(p=>({...p,name,h1:a.title??name,shortDescription:a.description??"",description:a.description??"",url:a.url,cover:{...p.cover,src:"",alt:"Composição tipográfica ilustrativa; imagem externa apenas analisada",}}));setPending(["Desafio e objetivo do projeto precisam de confirmação do responsável.","Funcionalidades, tecnologias e resultados comerciais não foram verificados.",...(a.imageUrl?["Confirme autorização para uso de imagens do site antes de publicar."]:[])]);setStatus("needs_info")}catch(e){setStatus("draft");setError(e instanceof Error?e.message:"Falha na análise.")}finally{setBusy(false)}}
 function upd<K extends keyof Project>(key:K,value:Project[K]){setDraft(p=>({...p,[key]:value}))}
 async function save(nextStatus:Status=status){setBusy(true);setError("");setNotice("");try{const method=selected?.id?"PATCH":"POST";const payload={...(selected?.id?{id:selected.id}:{}),project:{...draft,slug:draft.slug.trim(),name:draft.name.trim(),url:url.trim(),updatedAt:new Date().toISOString().slice(0,10)},status:nextStatus,sourceUrl:url.trim()||null,sourceFacts:facts,pendingConfirmations:pending};const r=await fetch("/api/admin/projetos",{method,headers,body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error);await load();setSelected(d.project);setDraft(d.project.project_data);setStatus(d.project.status);setNotice(nextStatus==="published"?"Projeto publicado.":"Rascunho salvo.")}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.")}finally{setBusy(false)}}
 async function signIn(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/admin/analytics/session",{method:"POST",headers,body:JSON.stringify({password})});const d=await r.json();if(!r.ok)throw Error(d.error);setAuthenticated(true);setPassword("");await load()}catch(e){setError(e instanceof Error?e.message:"Falha de autenticação")}finally{setBusy(false)}}
 return <section className={styles.page}>
 <p className={styles.eyebrow}>ADMINISTRAÇÃO DE CONTEÚDO</p><h1>Projetos e estudos de caso</h1><p>Importe uma URL pública ou revise um projeto existente. Análise externa não confirma código, tecnologias, vendas ou autorização de uso de conteúdo.</p>
 {!authenticated ? <form className={styles.editor} onSubmit={signIn}><label>Senha administrativa<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required /></label><button disabled={busy}>{busy?"Verificando…":"Entrar"}</button>{error?<p role="alert" className={styles.error}>{error}</p>:null}</form> : <><div className={styles.layout}><aside className={styles.list}><button onClick={fresh}>+ Novo projeto</button><label>Pesquisar<input value={filter} onChange={e=>setFilter(e.target.value)} /></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}><option>Todos</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}>{["Todos","draft","analyzing","needs_info","review","published","archived"].map(x=><option key={x}>{x}</option>)}</select></label><ul>{shown.map((r,i)=><li key={`${r.slug}-${i}`}><button onClick={()=>edit((rows.find(x=>x.slug===r.slug)??{...r,pending_confirmations:[],source_facts:{},id:undefined}) as Row)}><strong>{r.project_data.name}</strong><span>{r.status} · {r.project_data.category}</span></button></li>)}</ul></aside>
 <div className={styles.editor}><form onSubmit={e=>{e.preventDefault();void save(status==="published"?"review":status)}}><h2>{selected?`Editar: ${selected.project_data.name}`:"Criar projeto"}</h2><label>Importar projeto por URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://site-publico.example" /><small className={styles.fieldHint}>Lê título, descrição e imagem pública para sugerir dados; não analisa código ou resultados.</small></label><button type="button" disabled={busy||!url} onClick={()=>void inspect()}>{busy?"Analisando…":"Analisar URL"}</button>{analysis?<div className={styles.notice}><b>Metadados públicos encontrados</b><p>{analysis.title??"Título não encontrado"}</p><p>{analysis.description??"Descrição não encontrada"}</p><small>{analysis.notice}</small></div>:null}
 <div className={styles.grid}>
  <label>Nome<input required value={draft.name} onChange={e=>upd("name",e.target.value)} /><small className={styles.fieldHint}>Nome que aparecerá na lista e na página do projeto.</small></label>
  <label>Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={draft.slug} onChange={e=>upd("slug",e.target.value)} placeholder="nome-do-projeto" /><small className={styles.fieldHint}>Final da URL; use letras minúsculas e hífens.</small></label>
  <label>Categoria<input value={draft.category} onChange={e=>upd("category",e.target.value)} /><small className={styles.fieldHint}>Área de atuação do projeto.</small></label>
  <label>Tipo<input value={draft.type} onChange={e=>upd("type",e.target.value)} /><small className={styles.fieldHint}>Formato entregue, como site ou loja virtual.</small></label>
 </div>
 <label>Título da página<input value={draft.h1} onChange={e=>upd("h1",e.target.value)} /><small className={styles.fieldHint}>Título principal exibido na página pública.</small></label>
 <label>URL pública<input type="url" value={draft.url||url} onChange={e=>{upd("url",e.target.value);setUrl(e.target.value)}} /><small className={styles.fieldHint}>Endereço do projeto publicado, se houver.</small></label>
 <label>Imagem local aprovada<input value={draft.cover.src} onChange={e=>upd("cover",{...draft.cover,src:e.target.value})} placeholder="/projects/imagem.webp" /><small>Use uma imagem autorizada que já esteja em public/. Upload não disponível.</small></label>
 <label>Resumo<textarea value={draft.shortDescription} onChange={e=>upd("shortDescription",e.target.value)} /><small className={styles.fieldHint}>Descrição curta usada nos cartões e listagens.</small></label>
 <label>Apresentação<textarea value={draft.description} onChange={e=>upd("description",e.target.value)} /><small className={styles.fieldHint}>Contexto do projeto para a página de detalhes.</small></label>
 <label>Desafio <small className={styles.fieldHint}>Descreva a necessidade confirmada com o responsável.</small><textarea value={draft.problem} onChange={e=>upd("problem",e.target.value)} /></label>
 <label>Solução<textarea value={draft.solution} onChange={e=>upd("solution",e.target.value)} /><small className={styles.fieldHint}>Como o projeto respondeu ao desafio.</small></label>
 <label>Execução / recursos construídos<textarea value={draft.execution} onChange={e=>upd("execution",e.target.value)} /><small className={styles.fieldHint}>O que foi efetivamente desenvolvido ou entregue.</small></label>
 <label>Objetivo<textarea value={draft.objective} onChange={e=>upd("objective",e.target.value)} /><small className={styles.fieldHint}>Resultado pretendido; não descreva como alcançado sem confirmação.</small></label>
 <div className={styles.grid}>
  <label>Valor potencial para a marca<textarea value={draft.brandValue??""} onChange={e=>upd("brandValue",e.target.value)} /><small className={styles.fieldHint}>Benefício possível para identidade e posicionamento.</small></label>
  <label>Valor para o estabelecimento<textarea value={draft.businessValue??""} onChange={e=>upd("businessValue",e.target.value)} /><small className={styles.fieldHint}>Benefício possível para a operação do negócio.</small></label>
  <label>Contribuição possível para vendas<textarea value={draft.salesValue??""} onChange={e=>upd("salesValue",e.target.value)} /><small className={styles.fieldHint}>Hipótese de contribuição; não informe números não medidos.</small></label>
  <label>Oportunidades futuras<textarea value={draft.futureOpportunities??""} onChange={e=>upd("futureOpportunities",e.target.value)} /><small className={styles.fieldHint}>Melhorias que podem ser feitas depois.</small></label>
 </div>
 <div className={styles.grid}>
  <label>Decisões de projeto<textarea value={draft.decisions.join("\n")} onChange={e=>upd("decisions",fieldList(e.target.value))} /><small className={styles.fieldHint}>Uma decisão por linha e o motivo de cada escolha.</small></label>
  <label>Tags<textarea value={draft.tags.join("\n")} onChange={e=>upd("tags",fieldList(e.target.value))} /><small className={styles.fieldHint}>Uma palavra-chave por linha.</small></label>
  <label>Funcionalidades confirmadas<textarea value={draft.features.join("\n")} onChange={e=>upd("features",fieldList(e.target.value))} /><small className={styles.fieldHint}>Liste apenas recursos verificados, um por linha.</small></label>
  <label>Tecnologias confirmadas<textarea value={draft.stack.join("\n")} onChange={e=>upd("stack",fieldList(e.target.value))} /><small className={styles.fieldHint}>Stack validada com o responsável, uma por linha.</small></label>
 </div>
 <label>Pendências de confirmação<textarea value={pending.join("\n")} onChange={e=>setPending(fieldList(e.target.value))} /><small className={styles.fieldHint}>Informações que ainda precisam ser verificadas antes de publicar.</small></label>
 <p className={styles.status}>Status: {status}</p>{error?<p role="alert" className={styles.error}>{error}</p>:null}{notice?<p role="status" className={styles.notice}>{notice}</p>:null}<div className={styles.actions}><button disabled={busy||!draft.name||!draft.slug}>{status==="published"?"Salvar alterações para revisão":"Salvar rascunho"}</button>{selected?.id&&status!=="published"?<button type="button" disabled={busy} onClick={()=>void save("published")}>Publicar após revisão</button>:null}{selected?.id&&status==="published"?<button type="button" disabled={busy} onClick={()=>void save("archived")}>Despublicar / arquivar</button>:null}{selected?.id?<button type="button" onClick={async()=>{const r=await fetch(`/api/admin/projetos/${selected.id}/historico`);const d=await r.json();setNotice(JSON.stringify(d.revisions??[],null,2))}}>Histórico</button>:null}</div></form></div></div><button type="button" onClick={async()=>{await fetch("/api/admin/analytics/session",{method:"DELETE"});setAuthenticated(false)}}>Sair</button></>}</section>
}
